/**
 * SAMPLE / PLACEHOLDER PRODUCTS
 * ─────────────────────────────
 * These are shown ONLY when CONFIG.sheetCsvUrl (in js/config.js) is
 * empty. They exist so you can see the site fully working with a
 * real-looking catalog before you load your own products.
 *
 * Once you connect your Google Sheet, this file is ignored — you
 * never need to edit this file for day-to-day product updates.
 *
 * Image links below use placehold.co placeholder images. Replace
 * with real product photo links in your Google Sheet later.
 */
window.FALLBACK_PRODUCTS = [
  {
    id: "1",
    name: "Wireless Bluetooth Earbuds",
    category: "Electronics & Gadgets",
    price: 1999,
    oldPrice: 3500,
    image: "https://placehold.co/600x600/141414/d4af37?text=Bluetooth+Earbuds",
    rating: 4.6,
    reviews: 128,
    badge: "Hot",
    description: "Crisp sound, long battery life, comfy fit.",
    inStock: true,
  },
  {
    id: "2",
    name: "Smart Watch Fitness Tracker",
    category: "Electronics & Gadgets",
    price: 2499,
    oldPrice: "",
    image: "https://placehold.co/600x600/141414/d4af37?text=Smart+Watch",
    rating: 4.4,
    reviews: 76,
    badge: "",
    description: "Heart rate, steps, notifications on your wrist.",
    inStock: true,
  },
  {
    id: "3",
    name: "Portable Power Bank 20000mAh",
    category: "Electronics & Gadgets",
    price: 1499,
    oldPrice: 2200,
    image: "https://placehold.co/600x600/141414/d4af37?text=Power+Bank",
    rating: 4.7,
    reviews: 203,
    badge: "Best Seller",
    description: "Fast-charge two devices at once, all day power.",
    inStock: true,
  },
  {
    id: "4",
    name: "LED Ring Light with Tripod",
    category: "Electronics & Gadgets",
    price: 1800,
    oldPrice: "",
    image: "https://placehold.co/600x600/141414/d4af37?text=Ring+Light",
    rating: 4.3,
    reviews: 54,
    badge: "New",
    description: "Perfect lighting for content, calls and selfies.",
    inStock: true,
  },
  {
    id: "5",
    name: "Men's Leather Wallet",
    category: "Fashion & Accessories",
    price: 899,
    oldPrice: "",
    image: "https://placehold.co/600x600/1a1a1a/f2d675?text=Leather+Wallet",
    rating: 4.5,
    reviews: 61,
    badge: "",
    description: "Genuine leather, slim fit, multiple card slots.",
    inStock: true,
  },
  {
    id: "6",
    name: "Women's Handbag",
    category: "Fashion & Accessories",
    price: 1999,
    oldPrice: 2800,
    image: "https://placehold.co/600x600/1a1a1a/f2d675?text=Handbag",
    rating: 4.8,
    reviews: 142,
    badge: "Best Seller",
    description: "Elegant everyday handbag, spacious and durable.",
    inStock: true,
  },
  {
    id: "7",
    name: "Unisex Sunglasses",
    category: "Fashion & Accessories",
    price: 699,
    oldPrice: "",
    image: "https://placehold.co/600x600/1a1a1a/f2d675?text=Sunglasses",
    rating: 4.2,
    reviews: 39,
    badge: "",
    description: "UV protection with a classic, sharp look.",
    inStock: true,
  },
  {
    id: "8",
    name: "Non-Stick Cooking Pot Set",
    category: "Home & Kitchen",
    price: 3200,
    oldPrice: "",
    image: "https://placehold.co/600x600/141414/d4af37?text=Pot+Set",
    rating: 4.6,
    reviews: 88,
    badge: "",
    description: "5-piece set, even heat, easy to clean.",
    inStock: true,
  },
  {
    id: "9",
    name: "Electric Kettle 1.8L",
    category: "Home & Kitchen",
    price: 1650,
    oldPrice: "",
    image: "https://placehold.co/600x600/141414/d4af37?text=Electric+Kettle",
    rating: 4.5,
    reviews: 97,
    badge: "New",
    description: "Boils fast, auto shut-off, cordless base.",
    inStock: true,
  },
  {
    id: "10",
    name: "Blender & Juicer 2-in-1",
    category: "Home & Kitchen",
    price: 2750,
    oldPrice: 3500,
    image: "https://placehold.co/600x600/141414/d4af37?text=Blender",
    rating: 4.4,
    reviews: 65,
    badge: "",
    description: "Smoothies, juice and more in one machine.",
    inStock: true,
  },
  {
    id: "11",
    name: "Organic Shea Body Butter",
    category: "Beauty & Personal Care",
    price: 650,
    oldPrice: "",
    image: "https://placehold.co/600x600/1a1a1a/f2d675?text=Shea+Butter",
    rating: 4.9,
    reviews: 176,
    badge: "Best Seller",
    description: "100% natural, deep moisture for all skin types.",
    inStock: true,
  },
  {
    id: "12",
    name: "Hair Growth Oil Set",
    category: "Beauty & Personal Care",
    price: 1200,
    oldPrice: "",
    image: "https://placehold.co/600x600/1a1a1a/f2d675?text=Hair+Oil",
    rating: 4.3,
    reviews: 44,
    badge: "",
    description: "Nourishing blend for stronger, healthier hair.",
    inStock: true,
  },
  {
    id: "13",
    name: "Baby Diaper Bag",
    category: "Kids & Baby",
    price: 1750,
    oldPrice: "",
    image: "https://placehold.co/600x600/141414/d4af37?text=Diaper+Bag",
    rating: 4.6,
    reviews: 52,
    badge: "",
    description: "Spacious, stylish, with insulated bottle pockets.",
    inStock: true,
  },
  {
    id: "14",
    name: "Kids Educational Tablet",
    category: "Kids & Baby",
    price: 2999,
    oldPrice: "",
    image: "https://placehold.co/600x600/1a1a1a/f2d675?text=Kids+Tablet",
    rating: 4.1,
    reviews: 23,
    badge: "Sold Out",
    description: "Fun learning games and parental controls.",
    inStock: false,
  },
  {
    id: "15",
    name: "Yoga Mat Non-Slip",
    category: "Sports & Outdoor",
    price: 1100,
    oldPrice: "",
    image: "https://placehold.co/600x600/141414/d4af37?text=Yoga+Mat",
    rating: 4.5,
    reviews: 48,
    badge: "New",
    description: "Extra thick, non-slip, easy to carry.",
    inStock: true,
  },
];
